# Generated by Django 4.2.10 on 2024-04-28 19:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(choices=[('o+', 'O+'), ('o-', 'O-'), ('ab+', 'AB+'), ('ab-', 'AB-'), ('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_num', models.CharField(unique=True, validators=[django.core.validators.RegexValidator('(^[0-9]{4}-[0-9]{4}-[0-9]{5}$)|(^[0-9]{8}$)')])),
                ('patient_name', models.CharField(max_length=500)),
                ('patient_phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^0093\\d{9}')])),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('patient_date_of_birth', models.DateField()),
                ('patient_address', models.TextField(blank=True, null=True)),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodbank.bloodgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('volume', models.PositiveSmallIntegerField()),
                ('transfusion_date', models.DateTimeField(auto_now_add=True)),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodbank.bloodgroup')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodbank.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_num', models.CharField(unique=True, validators=[django.core.validators.RegexValidator('(^[0-9]{4}-[0-9]{4}-[0-9]{5}$)|(^[0-9]{8}$)')])),
                ('donor_name', models.CharField(max_length=500)),
                ('donor_phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^0093\\d{9}')])),
                ('donor_email', models.EmailField(max_length=254)),
                ('donor_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('donor_date_of_birth', models.DateField()),
                ('donor_address', models.TextField(blank=True, null=True)),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodbank.bloodgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('donation_volume', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(460)])),
                ('residual_volume', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(460)])),
                ('transfusion_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('1', 'Valid'), ('2', 'Invalid')], max_length=10)),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodbank.bloodgroup')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodbank.donor')),
            ],
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['id_num'], name='bloodbank_p_id_num_cfc5b0_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['id_num'], name='bloodbank_d_id_num_b6fdb4_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['id'], name='bloodbank_d_id_d98f61_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status'], name='bloodbank_d_status_716a48_idx'),
        ),
    ]
