# Generated by Django 4.2.10 on 2024-03-04 23:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(choices=[('o+', 'O+'), ('o-', 'O-'), ('ab+', 'AB+'), ('ab-', 'AB-'), ('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-')], max_length=5)),
                ('available_volume', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=500)),
                ('patient_phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^0093\\d{9}')])),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('patient_age', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(150)])),
                ('patient_address', models.TextField(blank=True, null=True)),
                ('volume', models.PositiveSmallIntegerField()),
                ('transfusion_date', models.DateTimeField(auto_now_add=True)),
                ('physician_name', models.CharField(blank=True, max_length=500, null=True)),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodbank.bloodgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('donor_name', models.CharField(max_length=500)),
                ('donor_phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^0093\\d{9}')])),
                ('donor_email', models.EmailField(max_length=254)),
                ('donor_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('donor_age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(65)])),
                ('donor_address', models.TextField(blank=True, null=True)),
                ('donation_volume', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(460)])),
                ('residual_volume', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(460)])),
                ('transfusion_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('1', 'Valid'), ('2', 'Invalid')], max_length=10)),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodbank.bloodgroup')),
            ],
        ),
    ]
