# Generated by Django 4.2.10 on 2024-03-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0002_remove_bloodgroup_available_volume'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['id'], name='bloodbank_d_id_d98f61_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status'], name='bloodbank_d_status_716a48_idx'),
        ),
    ]
